### ISSUE TITLE
Tighten up the spacing on the account registration form validation

### ISSUE THREAD

**Issue by verypolite-brendenmersey** [Very-Polite-Agency/studio-d-shopify#10]
Expected:
Error message on the account forms to be consistent with less generous padding.

Currently:
If a person is registering for an account, and there are errors present, the errors are all varying sizes and some have huge amounts of padding.

<img width="584" alt="Screen Shot 2022-05-27 at 11 56 25 PM" src="https://user-images.githubusercontent.com/99919082/170814660-8edbab11-8dc5-4ac8-9890-e96eb2193d0a.png">

<img width="643" alt="Screen Shot 2022-05-27 at 11 56 02 PM" src="https://user-images.githubusercontent.com/99919082/170814718-6e0b7d9f-c0c4-4b78-ba2d-5a148db180f4.png">

**Comment by miguelaf4** [comment]
I removed the weird paddings, and refactor the elements to be in the same style as the WordPress errors

![image](https://user-images.githubusercontent.com/34670748/170878100-fe118773-7c21-47c4-9ce4-2a8f482e62ea.png)
