### ISSUE TITLE
Swap the 'compare at price' styles and positioning

### ISSUE THREAD

**Issue by verypolite-brendenmersey** [Very-Polite-Agency/studio-d-shopify#11]
Expected: 
The lower-priced item should be first, followed by the higher-priced item. The higher-priced item should be 0.5 opacity with a line-through.

Currently:
<img width="163" alt="Screen Shot 2022-05-27 at 11 53 32 PM" src="https://user-images.githubusercontent.com/99919082/170814837-6d7fbcc3-3cee-4e02-95ba-3580fe47ab6f.png">

**Comment by miguelaf4** [comment]
I believe this is as expected.

Design: 
![image](https://user-images.githubusercontent.com/34670748/170877180-6840be97-9701-46a1-ac06-62ae593c1b9f.png)

Site:
![image](https://user-images.githubusercontent.com/34670748/170877192-656cb021-ebf3-4d7e-8069-8b4a3e5ad73e.png)
