### ISSUE TITLE
Overflow hidden bug when exiting the cart summary pop-up/drawer

### ISSUE THREAD

**Issue by verypolite-brendenmersey** [Very-Polite-Agency/studio-d-shopify#12]
Expected: 
When the cart summary drawer closes, the page should be scrollable.

Currently:
When the cart summary drawer is open and a user clicks continue shopping _or_ the 'x' in the top right corner, the drawer closes, but the overflow setting on the <body> stays.

<img width="419" alt="Screen Shot 2022-05-27 at 11 53 21 PM" src="https://user-images.githubusercontent.com/99919082/170814961-f84a8cab-ecc3-44bb-bec1-a1ebdbff01f9.png">

<img width="508" alt="Screen Shot 2022-05-27 at 11 52 47 PM" src="https://user-images.githubusercontent.com/99919082/170814965-dbf41a50-fa9b-4883-8f46-5974daf89617.png">

**Comment by miguelaf4** [comment]
So the buttons in the quick cart worked as expected. However in the product page, when clicking on the add to cart, this didn't add the same class to the body. I added the same functionality as the other buttons, so right now it should work.
