### ISSUE TITLE
Left align sub-navigation items on the mobile menu.

### ISSUE THREAD

**Issue by verypolite-brendenmersey** [Very-Polite-Agency/studio-d-shopify#13]
Expected: 
Sub-navigation items to be left-aligned on the mobile menu.

Currently:
<img width="485" alt="Screen Shot 2022-05-28 at 12 25 02 AM" src="https://user-images.githubusercontent.com/99919082/170815364-e8582470-6169-4d58-ab22-8b0374aa7880.png">

**Comment by miguelaf4** [comment]
The link class which I used for the buttons, was causing a problem. I fixed it

![image](https://user-images.githubusercontent.com/34670748/170876287-70da69c7-b9ea-477b-9a74-6706bc43ba27.png)
