### ISSUE TITLE
Footer styles do not match the WordPress site.

### ISSUE THREAD

**Issue by verypolite-brendenmersey** [Very-Polite-Agency/studio-d-shopify#2]
The CSS styling on the footer of the Shopify version of the site do not match the WordPress version. Please make the styles identical. There should be no difference between the sites.

**Comment by miguelaf4** [comment]
Ignoring the fact I accidentally put comas instead of a point, everything should look the same. I fixed the letter spacing.

![image](https://user-images.githubusercontent.com/34670748/170155394-af56d1c7-7846-4ca1-b3be-f947905c30d6.png)
