### ISSUE TITLE
Header navigation items hover state to match WordPress site

### ISSUE THREAD

**Issue by verypolite-brendenmersey** [Very-Polite-Agency/studio-d-shopify#6]
The hover state for the main navigation items on the desktop version of the header do not match the WordPress site. On WordPress the hover state is opacity: 0.3 with a transition duration of 0.3s.

**Comment by miguelaf4** [comment]
I changed the hover state to those settings

![image](https://user-images.githubusercontent.com/34670748/169924509-77e683a2-80e3-4aa2-8aec-887c194c9950.png)
