### ISSUE TITLE
Resize the content width of the fifty-fifty block.

### ISSUE THREAD

**Issue by verypolite-brendenmersey** [Very-Polite-Agency/studio-d-shopify#7]
Resize the content width of the fifty-fifty block. Use https://studiodhome.wpengine.com/our-serivces/ as reference. If you inspect the content (non-image side) of the fifty-fifty, it should have a max-width and some padding, etc.

**Comment by miguelaf4** [comment]
I have added the same styles depending on the side of the info
![image](https://user-images.githubusercontent.com/34670748/170762376-11efcdef-4124-4cf5-b419-751241d78637.png)

**Comment by verypolite-brendenmersey** [comment]
Expected:
At 992px and up (all desktop sizes) the fifty-fifty should reflect the same layout style on the WordPress site and the designs.

Currently:
Weird formatting at sizes 992px up to 1199px. It looks great at 1200px and larger, and 992px and below. Just the one breakpoint size.

![Screen Shot 2022-05-30 at 4 05 40 PM](https://user-images.githubusercontent.com/99919082/171066686-2357c369-2d96-4eca-8194-c0ea89f8ec48.png)

**Comment by miguelaf4** [comment]
There was a width: 100% that was affecting the column system

![image](https://user-images.githubusercontent.com/34670748/171067613-38e44645-df15-4c8e-83f7-c7b0af4e7de0.png)
