### ISSUE TITLE
Remove filter option from PLP

### ISSUE THREAD

**Issue by verypolite-brendenmersey** [Very-Polite-Agency/studio-d-shopify#8]
Expected:
Sort options only on the PLP, no filter.

Currently:
There are both filter and sort options. I think the design team brought it over from the old site not knowing how the system works - apologies for any confusion!

<img width="220" alt="Screen Shot 2022-05-27 at 11 58 11 PM" src="https://user-images.githubusercontent.com/99919082/170814452-f6ba37aa-71a1-4d49-833a-e0d97f80cd9d.png">

**Comment by miguelaf4** [comment]
Yup, it was a little bit confusing, but I thought it was just a label hahaha. I removed the 'Filter'. 

![image](https://user-images.githubusercontent.com/34670748/170876618-ceeca8b2-5b91-4ea8-867a-63fd6c1795c7.png)
