### ISSUE TITLE
Add wording to account overview/dashboard view when '0' orders

### ISSUE THREAD

**Issue by verypolite-brendenmersey** [Very-Polite-Agency/studio-d-shopify#9]
Expected:
When a user is in the account overview/dashboard and does not have any orders, there should be a fallback message to confirm no orders associated with the account.

If the order count is '0' drop in a simple line below the horizontal rule of the table: "It looks like there are no orders associated with this account!"

Currently:
<img width="759" alt="Screen Shot 2022-05-27 at 11 57 45 PM" src="https://user-images.githubusercontent.com/99919082/170814560-5e6ebc43-e481-488e-89a0-06fd32e5cc79.png">

**Comment by miguelaf4** [comment]
There was a missing conditional for this. I have fixed it

![image](https://user-images.githubusercontent.com/34670748/170879466-a67b49b1-b93b-4225-b394-40d5b3e966e4.png)
